# nvidia-smi-runner.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvidia-smi-runner
  labels:
    app: nvidia-smi-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvidia-smi-runner
  template:
    metadata:
      labels:
        app: nvidia-smi-runner
    spec:
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"

      containers:
      - name: nvidia-smi-container
        image: nvidia/cuda:12.1.0-base-ubuntu22.04
        command:
          - "/bin/sh"
          - "-c"
          - |
            echo "Starting nvidia-smi loop..."
            while true; do
              echo "--- $(date) ---"
              nvidia-smi
              echo "-------------------"
              sleep 5
            done
        resources:
          limits:
            nvidia.com/gpu: 1
          requests: # Optional, but good practice
            nvidia.com/gpu: 1

